# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and release

on:
  push:
    tags:
      - "v*.*"

jobs:

  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Run build script
        env:
#          APP_PLATFORMS: 'darwin/amd64,darwin/amd64-avx,darwin/arm64,windows/amd64,windows/amd64-avx,windows/386,windows/arm64,linux/amd64,linux/amd64-avx,linux/386,linux/arm,linux/armv5,linux/arm64,linux/s390x,linux/mipsle,linux/mipsle-sf,freebsd/amd64,freebsd/amd64-avx,freebsd/386,freebsd/arm,freebsd/arm64'
          APP_PLATFORMS: 'windows/amd64,windows/386,windows/arm64,linux/amd64,linux/386,linux/arm'
        run: ./build.sh
        shell: bash

      - name: Generate hashes
        run: |
          cd build
          for f in $(find . -type f); do
            sha256sum $f | sudo tee -a hashes.txt
          done

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./build/*
